import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PLACEHOLDER — hand-written stub, not generated by `flutterfire configure`. No real Firebase
/// project exists for SchoolOS yet (tracked in build/PROJECT-STATUS.md's Sprint F section).
/// These values are syntactically valid `FirebaseOptions` but will fail authentication against
/// Google's servers — which FirebaseMessagingTokenProvider (lib/src/notifications/push_token_provider.dart)
/// already treats as "push unavailable this session" and degrades gracefully from. Replace this
/// entire file by running `flutterfire configure` once a real Firebase project is created; do not
/// hand-edit these values to "make it work" — a project ID that doesn't exist will never succeed.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'placeholder-web-api-key',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'schoolos-placeholder',
  );

  static const android = FirebaseOptions(
    apiKey: 'placeholder-android-api-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'schoolos-placeholder',
  );

  static const ios = FirebaseOptions(
    apiKey: 'placeholder-ios-api-key',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'schoolos-placeholder',
    iosBundleId: 'pk.edu.schoolos.parent_app',
  );
}